### ISSUE TITLE
AIVA Consuming RAM

### ISSUE THREAD

**Issue by getsiddd** [kengz/aiva#32]
Why AIVA is consuming so much RAM, My computer hangs if i run command npm start ?

**Comment by kengz** [comment]
The total consumption is about 2Gb - mostly from the python NLP dependencies - [spaCy](https://spacy.io/) base instance takes about 1.7Gb, and the graph brain adds an extra 600Mb.

**Comment by getsiddd** [comment]
Is there any way we can optimize it?

**Comment by kengz** [comment]
Unfortunately not for now, it's running the spaCy instance as a plain python process. The issue is brought up [here on the spaCy page as well](https://github.com/explosion/spaCy/issues/260)

A way is to simply disable the feature together if it's not needed, i.e. by editing `config/default.json` to NOT run python, i.e. setting [this line on the live config file](https://github.com/kengz/aiva/blob/master/config/example-default.json#L14) to `false`.
